### ISSUE TITLE
HarmonyExportImportedSpecifierDependency.js error

### ISSUE THREAD

**Issue by wutongshuxia** [module-federation/module-federation-examples#1673]
I'm going to use the yarn start under the 《basic host remote project》, but this exception is exposed. I think this webpack version was changed 22 hours ago

HarmonyExportImportedSpecifierDependency.js:47
class N
 
SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/lizhikai/likai/education/webpack/module-federation-examples-master/basic-host-remote/node_modules/webpack/lib/dependencies/HarmonyModulesPlugin.js:13:50)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
error Command failed with exit code 2.

**Comment by ScriptedAlchemy** [comment]
Check the loaders are up to date it might be related otherwise open issue pointing to my project on webpack issues so they can diagnose it
