### ISSUE TITLE
ERROR in external and also Invalid request

### ISSUE THREAD

**Issue by AlonsoK28** [module-federation/module-federation-examples#2695]
I am triying to load a `remote` that was builded with `@angular-architects/module-federation/webpack` into a `host` that only uses pure `webpack` (no angular, no react, no vue)

When try to load the `remove` into `host` I'm getting the following error into `webpack` console:

```sh
ERROR in external "https://ng-ticket-invoice-mf.vercel.app/remoteEntry.js"
Invalid request "https://ng-ticket-invoice-mf.vercel.app/remoteEntry.js"
```

Additionally, I can comment that this `remote` is working well inside an angular `host` application.

### webpack config (host - only webback)
```js
//webpack
const path = require('path');
const webpack = require('webpack');

//webpack plugins
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");

//filesystem paths
const OUTPUT_PATH = path.resolve(__dirname, 'assets', 'js', 'webpack', 'dist/');
const PUBLIC_PATH = 'assets/js/webpack/dist/'; //don't remove

const share = mf.share;
const sharedMappings = new mf.SharedMappings();

module.exports = {
  entry: {
    ...
  },
  output: {
    filename: '[name].bundle.js',
    chunkFilename: 'chunks/[name].js', //used for lazy-modules
    path: OUTPUT_PATH,
    publicPath: PUBLIC_PATH
  },
  module: {
    rules: [ ... ]
  },
  resolve: {
    alias: {
      ...
    },
  },
  plugins: [
    new CleanWebpackPlugin(),
    new ModuleFederationPlugin({
      // For remotes (please adjust)
      // filename: "remoteEntry.js",
      // exposes: {
      //     './Component': './projects/my-admin-host/src/app/app.component.ts',
      // },        

      // For hosts (please adjust)
      remotes: {
        "ticketInvoiceMf": "https://ng-ticket-invoice-mf.vercel.app/remoteEntry.js",

      },

      shared: share({
        "@angular/core": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/common": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/router": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      })
      
    }),
  ],
  optimization: {
    splitChunks: {
      ...
    }
  }
}
```

### webpack config (remote - angular app)

```js
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");
const share = mf.share;

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, '../../tsconfig.json'),
  [/* mapped paths to share */]);

module.exports = {
  output: {
    uniqueName: "ticketInvoiceMf",
    publicPath: "auto"
  },
  optimization: {
    runtimeChunk: false
  },   
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    }
  },
  experiments: {
    outputModule: true
  },
  plugins: [
    new ModuleFederationPlugin({
      library: {
        type: "module"
      },

      // For remotes (please adjust)
      name: "ticketInvoiceMenu-mf",
      filename: "remoteEntry.js",
      exposes: {
        // my lazy module 
        './TicketInvoiceMenuModule':
          './projects/ticket-invoice-mf/src/app/components/ticket-invoice-menu/module/ticket-invoice-menu.module.ts',

        // only component
        './TicketInvoiceMenuComponent':
          './projects/ticket-invoice-mf/src/app/components/ticket-invoice-menu/ticket-invoice-menu.component.ts',

        // app module
        './AppModule':
          './projects/ticket-invoice-mf/src/app/app.module.ts'
      },
      shared: share({
        "@angular/core": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/common": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/router": { singleton: true, strictVersion: true, requiredVersion: 'auto' },

        ...sharedMappings.getDescriptors()
      })
    }),
    sharedMappings.getPlugin()
  ],
};

```

**Comment by ScriptedAlchemy** [comment]
It's supposed to be the @ syntax. Not a url as far as I recall. 

Global@url 

App1@http://

**Comment by AlonsoK28** [comment]
> It's supposed to be the @ syntax. Not a url as far as I recall.
> 
> Global@url
> 
> App1@http://

I have fixed like this and the error has gone

```js
remotes: {
 "app2mf": "app2mf@http://localhost:6161/remoteEntry.js",
},
```
Iam triying to call the AngularMF from `webpack 5` like this

```js
const button = document.querySelector('.module-federation');
  button.addEventListener('click', () => {
    import(/* webpackChunkName: "print" */ 'app2mf/ticketInvoiceMf')
    .then(module => {
      const print = module.default;
      print();
    })
  })
```

and Im getting the following error 

```js
contact.bundle.js:47 Uncaught (in promise) ScriptExternalLoadError: Loading script failed.
(missing: http://localhost:6161/remoteEntry.js)
while loading "./ticketInvoiceMf" from webpack/container/reference/app2mf
    at webpack/container/reference/app2mf (contacto.bundle.js:47:25)
    at __webpack_require__ (contact.bundle.js:84:41)
    at handleFunction (contact.bundle.js:319:30)
    at contact.bundle.js:338:14
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.remotes (contact.bundle.js:301:35)
    at contact.bundle.js:200:39
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (contact.bundle.js:199:66)
    at HTMLButtonElement.eval (contact.js:54:25)
```

**Comment by ScriptedAlchemy** [comment]
can it work with out library.type = module? 

if you use module then yes, youd use a normal http url and not the @ syntax since it uses native import() to load esm modules. 

It would seem youre mixing the wrong module formats between the webpack chunk loading system and MF configs, 

ESM requires a few options to be set, so id try without library.type module so see if that works on not

**Comment by ScriptedAlchemy** [comment]
and disable experimental module outputs etc
