### ISSUE TITLE
Build Failed on Vercel: Initialization of sharing external failed. 

### ISSUE THREAD

**Issue by alibek-gao** [module-federation/module-federation-examples#2876]
Deployment that has failed in the production environment on Vercel with following error:
```
Initialization of sharing external failed: TypeError: __webpack_modules__[moduleId] is not a function
```

I have same error on local machine, however build is OK.
It is strange because this project was deployed successfully on Vercel yesterday.

I checked last successful build and it also had same error, but build was OK

I **reverted all changes** in code and build fails anyway.

I submitted support ticket on Vercel.
But maybe this issue can be useful or solved here.

Repo: https://github.com/alibek-gao/mf-next-chakra-poc_layout

 <details>
  <summary>Failed build log</summary>

```
[22:57:43.637] Running build in San Francisco, USA (West) – sfo1
[22:57:43.693] Cloning github.com/alibek-gao/mf-next-chakra-poc_layout (Branch: main, Commit: c3a7eee)
[22:57:44.409] Cloning completed: 714.984ms
[22:57:45.617] Restored build cache
[22:57:45.637] Running "vercel build"
[22:57:46.063] Vercel CLI 28.17.0
[22:57:46.322] Running "install" command: `npm install`...
[22:57:47.903] 
[22:57:47.903] changed 1 package, and audited 498 packages in 1s
[22:57:47.903] 
[22:57:47.903] 111 packages are looking for funding
[22:57:47.903]   run `npm fund` for details
[22:57:47.904] 
[22:57:47.904] found 0 vulnerabilities
[22:57:47.913] Detected Next.js version: 13.2.4
[22:57:47.916] Running "npm run build"
[22:57:48.197] 
[22:57:48.197] > layout@0.1.0 build
[22:57:48.197] > next build
[22:57:48.198] 
[22:57:48.726] warn  - You have enabled experimental feature (esmExternals) in next.config.js.
[22:57:48.726] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[22:57:48.726] 
[22:57:48.857] info  - Linting and checking validity of types...
[22:57:50.417] info  - Creating an optimized production build...
[22:57:50.549] isServer false
[22:57:50.550] PRICING_APP_URL https://pricing.alibek.dev
[22:57:50.578] isServer true
[22:57:50.578] PRICING_APP_URL https://pricing.alibek.dev
[22:57:50.581] isServer true
[22:57:50.581] PRICING_APP_URL https://pricing.alibek.dev
[22:58:01.878] info  - Compiled successfully
[22:58:01.882] info  - Collecting page data...
[22:58:10.352] info  - Generating static pages (0/4)

[22:58:10.373] Initialization of sharing external failed: TypeError: __webpack_modules__[moduleId] is not a function
[22:58:10.383] Initialization of sharing external failed: TypeError: __webpack_modules__[moduleId] is not a function
[22:58:10.484] 
[22:58:10.484] Error occurred prerendering page "/features". Read more: https://nextjs.org/docs/messages/prerender-error
[22:58:10.485] Error: Shared module is not available for eager consumption: 6833
[22:58:10.485]     at __webpack_require__.m.<computed> (/vercel/path0/.next/server/webpack-runtime.js:610:54)
[22:58:10.485]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[22:58:10.485]     at 1451 (/vercel/path0/.next/server/chunks/451.js:25:24)
[22:58:10.485]     at Function.__webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[22:58:10.485] info  - Generating static pages (1/4)
[22:58:10.553] info  - Generating static pages (2/4)
[22:58:10.608] info  - Generating static pages (3/4)
[22:58:10.678] info  - Generating static pages (4/4)
[22:58:10.680] 
[22:58:10.680] > Build error occurred
[22:58:10.682] Error: Export encountered errors on following paths:
[22:58:10.682] 	/features
[22:58:10.683]     at /vercel/path0/node_modules/next/dist/export/index.js:425:19
[22:58:10.683]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[22:58:10.683]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[22:58:10.683]     at async /vercel/path0/node_modules/next/dist/build/index.js:1422:21
[22:58:10.684]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[22:58:10.684]     at async /vercel/path0/node_modules/next/dist/build/index.js:1280:17
[22:58:10.684]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
[22:58:10.684]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:73:29)
[22:58:10.769] Error: Command "npm run build" exited with 1
[22:58:11.042] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

 </details>

 <details>
  <summary>Last successful build log</summary>

```
[22:32:44.972] Running build in San Francisco, USA (West) – sfo1
[22:32:45.023] Cloning github.com/alibek-gao/mf-next-chakra-poc_layout (Branch: main, Commit: 8ee7c03)
[22:32:45.748] Cloning completed: 724.423ms
[22:32:47.025] Restored build cache
[22:32:47.046] Running "vercel build"
[22:32:47.483] Vercel CLI 28.17.0
[22:32:47.745] Installing dependencies...
[22:32:49.362] 
[22:32:49.362] changed 1 package in 1s
[22:32:49.363] 
[22:32:49.363] 111 packages are looking for funding
[22:32:49.363]   run `npm fund` for details
[22:32:49.372] Detected Next.js version: 13.2.4
[22:32:49.376] Detected `package-lock.json` generated by npm 7+...
[22:32:49.377] Running "npm run build"
[22:32:49.682] 
[22:32:49.683] > layout@0.1.0 build
[22:32:49.683] > next build
[22:32:49.683] 
[22:32:50.236] warn  - You have enabled experimental feature (esmExternals) in next.config.js.
[22:32:50.237] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[22:32:50.237] 
[22:32:50.372] info  - Linting and checking validity of types...
[22:32:51.992] info  - Creating an optimized production build...
[22:33:04.332] info  - Compiled successfully
[22:33:04.336] info  - Collecting page data...
[22:33:13.713] info  - Generating static pages (0/4)

[22:33:13.735] Initialization of sharing external failed: TypeError: __webpack_modules__[moduleId] is not a function
[22:33:13.747] Initialization of sharing external failed: TypeError: __webpack_modules__[moduleId] is not a function
[22:33:14.002] info  - Generating static pages (1/4)
[22:33:14.031] info  - Generating static pages (2/4)
[22:33:14.035] info  - Generating static pages (3/4)
[22:33:15.044] info  - Generating static pages (4/4)
[22:33:15.056] info  - Finalizing page optimization...

[22:33:15.059] 
[22:33:15.080] Route (pages)                              Size     First Load JS
[22:33:15.081] ┌ ○ / (319 ms)                             295 B           269 kB
[22:33:15.081] ├   /_app                                  0 B             269 kB
[22:33:15.081] ├ ○ /404                                   184 B           269 kB
[22:33:15.081] ├ ○ /features                              317 B           269 kB
[22:33:15.081] ├ λ /pricing                               767 B           270 kB
[22:33:15.081] └ λ /pricing2                              303 B           269 kB
[22:33:15.081] + First Load JS shared by all              269 kB
[22:33:15.081]   ├ chunks/framework-73b8966a3c579ab0.js   45.2 kB
[22:33:15.081]   ├ chunks/main-aca13a3d69935060.js        212 kB
[22:33:15.081]   ├ chunks/pages/_app-b6e4fc1c3cf0ad64.js  5.09 kB
[22:33:15.081]   └ chunks/webpack-8d7668b50f75e0db.js     7.19 kB
[22:33:15.082] 
[22:33:15.082] λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
[22:33:15.082] ○  (Static)  automatically rendered as static HTML (uses no initial props)
[22:33:15.082] 
[22:33:17.764] Traced Next.js server files in: 2.024s
[22:33:18.316] Created all serverless functions in: 552.121ms
[22:33:18.342] Collected static files (public/, static/, .next/static): 15.714ms
[22:33:18.887] Build Completed in /vercel/output [31s]
[22:33:24.282] Generated build outputs:
[22:33:24.283]  - Static files: 43
[22:33:24.284]  - Prerenders: 0
[22:33:24.284]  - Serverless Functions: 2
[22:33:24.284]  - Edge Functions: 0
[22:33:24.284] Serverless regions: Washington, D.C., USA
[22:33:24.284] Deployed outputs in 3s
[22:33:24.689] Build completed
[22:33:29.392] Uploading build cache [75.03 MB]...
[22:33:31.397] Build cache uploaded: 2.005s
```

 </details>

**Comment by alibek-gao** [comment]
After removing `automaticAsyncBoundary: true` in `next.config.js` I was able to deploy. 

idk if related, I have another issue regarding `automaticAsyncBoundary: true`
https://github.com/module-federation/universe/issues/670

**Comment by ScriptedAlchemy** [comment]
Yeah it might be - this initialization issue will go away completely in v7 release as im moving it to use delegate modules. 

You can check the readme of nextjs-mf so see more about delegates and can use that over the older built-in pattern which can have this issue
