### ISSUE TITLE
different-react-versions-16-18 warning

### ISSUE THREAD

**Issue by alissoncorsair** [module-federation/module-federation-examples#3106]
Everytime the component from the react 18 is rendered on the react 16 host, there is a warning in the browser console: "Warning:: ReactDOM.render is no longer supported in React 18. Use createRoot instead"

How can it be fixed?

**Comment by ScriptedAlchemy** [comment]
@brunos3d might have some input here. Im guessing youd need to pass a prop or some logic to check if its createRoot exists, if not then it uses render

**Comment by dkaus1** [comment]
Hi @ScriptedAlchemy  - My host app is on react version 16.12 and remote app react version is 18.  Now I'm trying to consume a functional component from remote app to host app, running into below error in console.

Just a background on the implementation  -  I am trying to consume for functional component in class based components 
 
`Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See [https://fb.me/react-crossorigin-error](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffb.me%2Freact-crossorigin-error&data=0
    at Object.invokeGuardedCallbackDev (react-dom.development.js:396:1)
   at invokeGuardedCallback (react-dom.development.js:440:1)
    at beginWork$$1 (react-dom.development.js:25780:1)
    at performUnitOfWork (react-dom.development.js:24695:1)
    at workLoopSync (react-dom.development.js:24671:1)
    at performSyncWorkOnRoot (react-dom.development.js:24270:1)
    at react-dom.development.js:12199:1
    at unstable_runWithPriority (scheduler.development.js:697:1)
    at runWithPriority$2 (react-dom.development.js:12149:1)`
 
 
`react.development.js:1659  Uncaught TypeError: Cannot read properties of null (reading 'useDebugValue')
    at useDebugValue (react.development.js:1659:1)
    at styled-components.browser.esm.js:1:18631
    at O (styled-components.browser.esm.js:1:19524)
    at renderWithHooks (react-dom.development.js:16260:1)
    at updateForwardRef (react-dom.development.js:18143:1)
    at beginWork$1 (react-dom.development.js:20211:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385:1)
    at invokeGuardedCallback (react-dom.development.js:440:1)
    at beginWork$$1 (react-dom.development.js:25780:1)`
    
    
   Any pointers to fix this issue?

**Comment by ScriptedAlchemy** [comment]
Mount it as two different apps?
