### ISSUE TITLE
React SSR host connecting to NextJS remote component - useEffect TypeError

### ISSUE THREAD

**Issue by lukewhitehouse** [module-federation/module-federation-examples#3115]
Hi there,

I've put together a forked example app showing an error I'm seeing when sharing components between a NextJS SSR remote and a React SSR host.

When running the host application, the remote component tries to load but fails when trying to resolve the `useEffect` that is in the component.

```
TypeError: Cannot read properties of null (reading 'useEffect')
     at useEffect (/path/to/module-federation-examples/nextjs-ssr-react-18-ssr/node_modules/react/cjs/react.development.js:1634:21)
     at ExportredTitle (webpack-internal:///./components/exposedTitle.js:13:53)
     at pn (/path/to/module-federation-examples/nextjs-ssr-react-18-ssr/about/dist/server/427.js:2:72535)
     at mn (/path/to/module-federation-examples/nextjs-ssr-react-18-ssr/about/dist/server/427.js:2:73311)
     at mn (/path/to/module-federation-examples/nextjs-ssr-react-18-ssr/about/dist/server/427.js:2:75226)
     at yn (/path/to/module-federation-examples/nextjs-ssr-react-18-ssr/about/dist/server/427.js:2:80487)
     at Tn (/path/to/module-federation-examples/nextjs-ssr-react-18-ssr/about/dist/server/427.js:2:83878)
```

Removing the `useEffect` from the component works fine, it's just when using `useEffect`. Presumably other React named exports will do the same.

I've tried the `requiredVersion: false` technique for the `react` dependency but that doesn't seem to be working unless I'm doing something wrong.

### Steps to recreate
- Clone https://github.com/lukewhitehouse/module-federation-examples/tree/example-nextjs-react-ssr
- Navigate to the new [nextjs-ssr-react-18-ssr](https://github.com/lukewhitehouse/module-federation-examples/tree/example-nextjs-react-ssr/nextjs-ssr-react-18-ssr) example.
- Run yarn start
- Go to http://localhost:3003

#### Example app structure 
Structure-wise, the example project is set up exactly like [nextjs-ssr](https://github.com/module-federation/module-federation-examples/tree/master/nextjs-ssr) but with an additional `about` application, which is taken from the [shell](https://github.com/module-federation/module-federation-examples/tree/master/react-18-ssr/shell) application within the [react-18-ssr](https://github.com/module-federation/module-federation-examples/tree/master/react-18-ssr) example.

```
nextjs-ssr-react-18-ssr/
    about/           // react-18-ssr
    checkout/        // nextjs-ssr
    home/            // nextjs-ssr
    shop/            // nextjs-ssr
```

Any ideas? :)

**Comment by lukewhitehouse** [comment]
Bumping this, anyone else having similar issues? @ScriptedAlchemy maybe?

**Comment by ScriptedAlchemy** [comment]
react is external in ssr, it will expect your host to be external too so it can just require() react
