### ISSUE TITLE
Next Federation Plugin not work with Webpack 5 Module Federation (Next app: HOST | React app: REMOTE)

### ISSUE THREAD

**Issue by LukNasc** [module-federation/module-federation-examples#3174]
I have a Next application, which must consume a remote React application, both are configured for module federation, Next using @module-federation/nextjs-mf and the react app using webpack 5, but following the examples I found here does not work when I try to check whether it is a server or not. Follow the examples and errors.

*Host - NextJS*
```ts
const { NextFederationPlugin } = require("@module-federation/nextjs-mf");

const remotes = (isServer) => {
  const location = isServer ? "ssr" : "chunks";
  return {
    remote: `remote@http://localhost:3009/bundle.js`,
  };
};

/**@type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack(config, { isServer }) {
    if (!isServer) {
      config.plugins.push(
        new NextFederationPlugin({
          name: "root",
          filename: "static/chunks/bundle.js",
          remotes: remotes(isServer),
        })
      );
    }
    return config;
  },
};

module.exports = nextConfig;
```

*Remote - React*
```js
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { ModuleFederationPlugin } = require("webpack").container;
const path = require("path");

module.exports = {
  ...
  plugins: [
    new ModuleFederationPlugin({
      name: "remote",
      library: { type: "var", name: "remote" },
      filename: "bundle.js",
      exposes: {
        "./Nav": "./src/Nav.js",
      },
      shared: {
        react: {
          singleton: true,
          version: "0",
          requiredVersion: false,
        },
        "react-dom": {
          singleton: true,
          version: "0",
          requiredVersion: false,
        },
      },
    }),
  ],
};

```

But i had this error:

![image](https://github.com/module-federation/module-federation-examples/assets/26725196/bff880ef-5844-43f6-ad2a-02f30694559f)

Does anyone have an idea how to solve it?

**Comment by RussellCanfield** [comment]
How are you handling the type for the module “remote/Nav” ?

**Comment by LukNasc** [comment]
@RussellCanfield 
I created a module.d.ts file and defined the "remote/Nav" module, like this:
```ts
declare module "remote/Nav"
```

But the problem is when I check if it is a server or not in next.config, because when I remove that, the error disappears and it shows me the error that the remote app was unable to load

**Comment by LukNasc** [comment]
When I make this change, I remove the "isServer" check.

```js
const { NextFederationPlugin } = require("@module-federation/nextjs-mf");

const remotes = (isServer) => {
  const location = isServer ? "ssr" : "chunks";
  return {
    remote: `remote@http://localhost:3009/bundle.js`,
  };
};

/**@type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack(config, { isServer }) {
-    if (!isServer) {
      config.plugins.push(
        new NextFederationPlugin({
          name: "root",
          filename: "static/chunks/bundle.js",
          remotes: remotes(isServer),
        })
      );
-   }
    return config;
  },
};

module.exports = nextConfig;
```
the previous error disappears and this appears:

```sh
executeLoad hit catch block ReferenceError: self is not defined
    at node-federation-loader-remote.vm:1193:12
    at node-federation-loader-remote.vm:1692:12
    at node-federation-loader-remote.vm:1704:12
    at C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:1186:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
container is offline, returning fake remote
Error [ScriptExternalLoadError]: Loading script failed.
(undefined: http://localhost:3009/bundle.js?1697478484498 or global var remote)
    at loadScript (webpack-internal:///./node_modules/@module-federation/nextjs-mf/src/default-delegate.js?remote=remote@http://localhost:3009/bundle.js:42:35)
    at importDelegatedModule (webpack-internal:///./node_modules/@module-federation/nextjs-mf/src/default-delegate.js?remote=remote@http://localhost:3009/bundle.js:169:12)
    at eval (webpack-internal:///./node_modules/@module-federation/nextjs-mf/src/default-delegate.js?remote=remote@http://localhost:3009/bundle.js:243:5)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///./node_modules/@module-federation/nextjs-mf/src/default-delegate.js?remote=remote@http://localhost:3009/bundle.js:238:18)
    at Object../node_modules/@module-federation/nextjs-mf/src/default-delegate.js?remote=remote@http://localhost:3009/bundle.js (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:59:1)
    at __webpack_require__ (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:85:42)
    at initExternal (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:376:28)
    at Function.__webpack_require__.I (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:395:15)
    at attachRemote (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:867:33)
    at C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:878:13
    at Function.__webpack_require__.O (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:128:23)
    at Function.installChunk (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:1157:33)
    at Function.__webpack_require__.C (C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\webpack-runtime.js:1357:32)
    at C:\Users\x\x\x\x\x\root-sample-next-js\.next\server\pages\_document.js:634:21 {
  type: undefined,
  request: 'http://localhost:3009/bundle.js?1697478484498'
}
```

**Comment by LukNasc** [comment]
Hello, I managed to solve the problem using React.lazy and React.Suspense to load the remote app
