### ISSUE TITLE
"simple-node" example fails if update  "@module-federation/node" dependency to "2.0.11"

### ISSUE THREAD

**Issue by Notalot** [module-federation/module-federation-examples#3635]
Steps to reproduce:

1. In all folders inside "[simple-node](https://github.com/module-federation/module-federation-examples/tree/master/simple-node)" update "@module-federation/node" dependency version from "2.0.2-beta.6" to "2.0.11".
2. In root folder of "[simple-node](https://github.com/module-federation/module-federation-examples/tree/master/simple-node)" example install all dependencies, then install dependencies in all folders inside: "[node-remote](https://github.com/module-federation/module-federation-examples/tree/master/simple-node/node-remote)", "[node-local-remote](https://github.com/module-federation/module-federation-examples/tree/master/simple-node/node-local-remote)", "[node-host](https://github.com/module-federation/module-federation-examples/tree/master/simple-node/node-host)". All instalments are successful.
3. In root folder run `pnpm start`.

What I see in console:

for "[node-remote](https://github.com/module-federation/module-federation-examples/tree/master/simple-node/node-remote)" and "[node-local-remote](https://github.com/module-federation/module-federation-examples/tree/master/simple-node/node-local-remote)" builds are successful, but "[node-host](https://github.com/module-federation/module-federation-examples/tree/master/simple-node/node-host)" fails with error

```
/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:5531
[2] /******/                                        if (typeof globalThis.__remote_scope__[remoteName] !== 'undefined') return callback(globalThis.__remote_scope__[remoteName]);
[2]                                                                                       ^
[2] 
[2] TypeError: Cannot read properties of undefined (reading 'node_remote')
[2]     at executeLoad (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:5531:64)
[2]     at __webpack_require__.l (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:5564:14)
[2]     at /Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:4542:22
[2]     at new Promise (<anonymous>)
[2]     at webpack/container/reference/node_remote (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:4540:18)
[2]     at __webpack_require__ (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:4581:33)
[2]     at initExternal (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:4867:28)
[2]     at __webpack_require__.I (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:4879:15)
[2]     at handleFunction (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:3844:35)
[2]     at onExternal (/Users/chekalova/WebstormProjects/module-federation-examples-new/simple-node/node-host/dist/server.js:3862:35)
[2] 
[2] Node.js v20.8.1
```
<img width="1436" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/18391283/2373270b-1160-4369-99f5-f705e2e7bdf9">

---

I understand that there are too many examples to update each and every with the latest versions, I would be happy to contribute myself, but I do not know where a problem is.

**Comment by ScriptedAlchemy** [comment]
ill have a look at this one, i think it still uses global scopes that are no longer implemented and instead we have the module-federation/runtime package which can be used to dynamic load things etc.

**Comment by ScriptedAlchemy** [comment]
use the `next` tag, its in canary right now, but should be fixed there.

 https://github.com/module-federation/module-federation-examples/pull/3665
