### ISSUE TITLE
Server-side rendering does not work with Module Federation

### ISSUE THREAD

**Issue by suhanw** [module-federation/module-federation-examples#564]
Hi! Appreciate any help/insight on making SSR work with Module Federation. 

Minimal reproducible repo: https://github.com/suhanw/wp5-ssr
README has the instructions to run locally. I was following this [example](https://github.com/module-federation/module-federation-examples/tree/408ced256b23206aac3b9c117ac63af73a504e2d/server-side-render-only) when creating this project. 

**What is the current behavior?**

I am able to build and start the host and remote servers successfully, but I get this server error when loading the page in the browser. 
```
Error: Cannot find module 'webpack/container/reference/remote'
Require stack:
- /Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js
while loading "./top-nav" from webpack/container/reference/remote
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.webpack/container/reference/remote (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:196:18)
    at __webpack_require__ (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:219:41)
    at handleFunction (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:325:31)
    at /Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:344:15
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.remotes (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:307:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js'
  ]
}
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/server_renderer_js.bundle.js:44:41)
    at _callee$ (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:106:39)
    at tryCatch (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:89:103)
    at _next (/Users/suhanwijaya/Desktop/temp/test/wp5-ssr/host/build/server/bundle.js:91:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproducible repo: https://github.com/suhanw/wp5-ssr
README has the instructions to run locally.

`host` server webpack config: https://github.com/suhanw/wp5-ssr/blob/main/host/webpack.server.config.js
`remote` server webpack config: https://github.com/suhanw/wp5-ssr/blob/main/remote/webpack.server.config.js

`remote` exposes the component `TopNav`, and `host` consumes and imports `TopNav` in the `App` component, here: 
https://github.com/suhanw/wp5-ssr/blob/main/host/client/components/App/index.js#L3
Sidenote: if you comment out the line above, SSR works (i.e., the `App` component is rendered on server-side correctly). 

**What is the expected behavior?**

`host` should be able to consume shared components exposed by `remote` for server-side rendering.

**Other relevant information:**
webpack version:  5.12.1
React version: 17.0.1
Node.js version: 14.15.3
Operating System: MacOS Catalina 10.15.6
Additional tools: None

**Comment by ckken** [comment]
mark

**Comment by suhanw** [comment]
@ckken sorry should I add more info?

**Comment by jacob-ebey** [comment]
@suhanw https://github.com/suhanw/wp5-ssr/pull/1

**Comment by jacob-ebey** [comment]
I have submitted a PR to webpack-node-externals, let's see if it takes: https://github.com/liady/webpack-node-externals/pull/92
