### ISSUE TITLE
workspace break the basic-host-remote example

### ISSUE THREAD

**Issue by lili21** [module-federation/module-federation-examples#702]
error message

```bash
lerna ERR! yarn run start stderr:
[webpack-cli] TypeError: cli.isValidationError is not a function
    at Command.<anonymous> (/Users/admin/Work/learn/module-federation-examples/basic-host-remote/node_modules/@webpack-cli/serve/lib/index.js:96:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/admin/Work/learn/module-federation-examples/basic-host-remote/node_modules/webpack-cli/lib/webpack-cli.js:708:13)
error Command failed with exit code 2.
```

**Comment by ndronov** [comment]
try update webpack-cli to v.4.5.0

**Comment by johnschult** [comment]
it's not just the `basic-host-remote` example that's broken, it's all of them.

**Comment by johnschult** [comment]
The `webpack-cli` package is out of date in many of the examples. To fix it, in each app's `package.json` where it is out of date, or not working, change it to:

`"webpack-cli": "^4.x",`

Then
```
$ yarn
$ yarn start
```
