### ISSUE TITLE
Unexpected token: operator (!==) when building host app

### ISSUE THREAD

**Issue by tmkasun** [module-federation/module-federation-examples#757]
Hi All,

First, Thank you all for introducing this module federation method to webpack.

I followed [basic host remote](https://github.com/module-federation/module-federation-examples/tree/master/basic-host-remote)  example pattern, and

I got following error when running a production build in webpack.
```java
ERROR in main.c759254c956de7e37d70.js from Terser
Unexpected token: operator (!==) [external "application_b":3,0][main.c759254c956de7e37d70.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

ERROR in main.59760e1e42431bc60e23.js from Terser
Unexpected token: operator (!==) [main.59760e1e42431bc60e23.js:21,12]
    at js_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:550:11)
    at croak (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:1288:9)
    at expr_atom (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:2525:9)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3294:19)
    at maybe_unary (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3289:57)
    at expr_ops (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3345:24)
    at maybe_conditional (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3350:20)
    at maybe_assign (/Users/user/testing/modulefederation/app1/node_modules/terser/dist/bundle.min.js:3427:20)

webpack 5.36.1 compiled with 2 errors in 8185 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_module_federation_app1@1.0.0 build:prod: `npm run clean && webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_module_federation_app1@1.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-04-30T10_56_02_416Z-debug.log
```

Below is my App1 (Host app) webpack config,

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');

const config = {
  entry: [
    './source/index.jsx',
  ],
  output: {
    path: path.resolve(__dirname, 'public'),
    filename: '[name].[contenthash].js',
    publicPath: 'auto',
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      'react-dom': '@hot-loader/react-dom',
    },
  },
  devtool: 'source-map',
  plugins: [
    new HtmlWebpackPlugin({
      template: 'source/assets/index.html',
    }),
    // New
    new ModuleFederationPlugin({
      name: 'application_master',
      remotes: {
        application_b: 'application_b',
      },
      shared: ['react', 'react-dom', '@material-ui/core', '@material-ui/icons', 'react-router-dom'],
    }),
  ],
};

module.exports = () => {
  return config;
};
```

I have noticed that In the example [application 1](https://github.com/module-federation/module-federation-examples/blob/master/basic-host-remote/app1/webpack.config.js#L39) It has used the remote hostname with `@http://remote.host.name/remoteEntry.js` when defining the remotes.

But in my case , I have used a `<script>` tag to import the remote entry file, Hence I omit the entry file path in my webpack config 
like below

```js
remotes: {
        application_b: 'application_b',
      },
```
Is this an invalid config ?

If I provide the hostname in the remote value, OR if I define an expose component and library config(then no need to provide entry file), It builds successfully.

example 

```js
new ModuleFederationPlugin({
      name: 'application_master',
      library: { type: 'var', name: 'application_master' },
      filename: 'masterRemoteEntry.js',
      exposes: {
        welcomeFromA: './source/Application/pages/Welcome.jsx',
      },
      remotes: {
        application_b: 'application_b',
      },
      shared: ['react', 'react-dom', '@material-ui/core', '@material-ui/icons', 'react-router-dom'],
    }),
```

Above config also works fine,

Why do I need to give a remote entry file when I'm not exposing any component in the remotes?

**Comment by jacob-ebey** [comment]
The remote entry file contains the runtime for things like sharing / loading deps as well as the chunk loading. Doing runtime single might be a way around not having a separate entry when you don't expose anything but that's all you if you want to explore it.

**Comment by tmkasun** [comment]
Thanks @jacob-ebey  for the response, I raised this concern in the webpack repo https://github.com/webpack/webpack/issues/13287 as well, And it seems there is an issue in the webpack validation logic

**Comment by ScriptedAlchemy** [comment]
you need to specify the library as `var` if you don't, the default webpack looks for is different. So when you're remotes are simply a string like application_b, you need application_b to have ```  library: { type: 'var', name: 'application_b' },``` in order for webpack to know how to attach it properly. It defaults to the global@http syntax
