### ISSUE TITLE
NextJS example  ReferenceError: __non_webpack_require__ is not defined

### ISSUE THREAD

**Issue by Kaipi360** [module-federation/module-federation-examples#829]
Hello,

I've been trying to run the example of **nextjs** folder and I'm getting this error all the time:

```
 ReferenceError: __non_webpack_require__ is not defined
[0]     at patchSharing (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/@module-federation/nextjs-mf/patchSharing.js:7:46)
[0]     at MyDocument.render (webpack-internal:///./pages/_document.js:34:8)
[0]     at processChild (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
[0]     at resolve (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
[0]     at ReactDOMServerRenderer.render (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
[0]     at ReactDOMServerRenderer.read (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
[0]     at renderToStaticMarkup (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:4004:27)
[0]     at renderDocument (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/render.js:3:749)
[0]     at renderToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/render.js:55:698)
[0]     at async /Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:112:97
[0]     at async /Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:105:142
[0]     at async DevServer.renderToHTMLWithComponents (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:137:387)
[0]     at async DevServer.renderErrorToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:139:492)
[0]     at async DevServer.renderErrorToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/server/next-dev-server.js:36:1380)
[0]     at async DevServer.renderToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:138:1629)
[0]     at async DevServer.renderToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/server/next-dev-server.js:36:578)
[0] ReferenceError: __non_webpack_require__ is not defined
[0]     at patchSharing (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/@module-federation/nextjs-mf/patchSharing.js:7:46)
[0]     at MyDocument.render (webpack-internal:///./pages/_document.js:34:8)
[0]     at processChild (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
[0]     at resolve (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
[0]     at ReactDOMServerRenderer.render (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
[0]     at ReactDOMServerRenderer.read (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
[0]     at renderToStaticMarkup (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/react-dom/cjs/react-dom-server.node.development.js:4004:27)
[0]     at renderDocument (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/render.js:3:749)
[0]     at renderToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/render.js:55:698)
[0]     at runMicrotasks (<anonymous>)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0]     at async /Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:112:97
[0]     at async /Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:105:142
[0]     at async DevServer.renderToHTMLWithComponents (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:137:387)
[0]     at async DevServer.renderToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/next-server/server/next-server.js:138:610)
[0]     at async DevServer.renderToHTML (/Users/xxxx/Projects/module-federation-examples-master/nextjs/next1/node_modules/next/dist/server/next-dev-server.js:36:578)
```

I've tried before to implement **nextjs-mf** in my project but it shows me the same issue...

Please can you help me?
Thanks.

**Comment by ScriptedAlchemy** [comment]
been fixec
