### ISSUE TITLE
nextjs example seems broken

### ISSUE THREAD

**Issue by josselinbuils** [module-federation/module-federation-examples#936]
Hello,

When I try to run the last version of **nextjs** example, I get the following error when opening http://localhost:3001:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js?aef8:1476)
    at useEffect (react.development.js?aef8:1519)
    at ExportredTitle (webpack-internal:///./components/exposedTitle.js:19)
    at renderWithHooks (react-dom.development.js?f8c1:14985)
    at mountIndeterminateComponent (react-dom.development.js?f8c1:17811)
    at beginWork (react-dom.development.js?f8c1:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js?f8c1:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?f8c1:3994)
    at invokeGuardedCallback (react-dom.development.js?f8c1:4056)
    at beginWork$1 (react-dom.development.js?f8c1:23964)
    at performUnitOfWork (react-dom.development.js?f8c1:22776)
    at workLoopSync (react-dom.development.js?f8c1:22707)
    at renderRootSync (react-dom.development.js?f8c1:22670)
    at performSyncWorkOnRoot (react-dom.development.js?f8c1:22293)
    at eval (react-dom.development.js?f8c1:11327)
    at unstable_runWithPriority (scheduler.development.js?bacd:468)
    at runWithPriority$1 (react-dom.development.js?f8c1:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js?f8c1:11322)
    at flushSyncCallbackQueue (react-dom.development.js?f8c1:11309)
    at scheduleUpdateOnFiber (react-dom.development.js?f8c1:21893)
    at dispatchAction (react-dom.development.js?f8c1:16139)
    at checkForUpdates (webpack-internal:///../node_modules/use-subscription/cjs/use-subscription.development.js:85)
    at eval (webpack-internal:///../node_modules/next/dist/next-server/lib/loadable.js:307)
    at Set.forEach (<anonymous>)
    at LoadableSubscription._update (webpack-internal:///../node_modules/next/dist/next-server/lib/loadable.js:306)
    at eval (webpack-internal:///../node_modules/next/dist/next-server/lib/loadable.js:286)

The above error occurred in the <ExportredTitle> component:

    at ExportredTitle (webpack-internal:///./components/exposedTitle.js:19:51)
    at LoadableComponent (webpack-internal:///../node_modules/next/dist/next-server/lib/loadable.js:188:37)
    at div
    at div
    at Home (webpack-internal:///./pages/index.js:44:21)
    at MyApp (webpack-internal:///./pages/_app.js:75:24)
    at ErrorBoundary (webpack-internal:///../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///../node_modules/next/dist/client/index.js:155:5)
    at AppContainer (webpack-internal:///../node_modules/next/dist/client/index.js:643:24)
    at Root (webpack-internal:///../node_modules/next/dist/client/index.js:779:25)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js?f8c1:20085
```

Usually it means that 2 instances of React are used but Module Federation plugin is set up to share React.

Does someone know where it could come from?

**Comment by ScriptedAlchemy** [comment]
I fixed it and have a PR open, but moving forwards next will depend on a paid plugin

**Comment by markhughes** [comment]
@ScriptedAlchemy how much are you charging for the paid plugin, where can we read more about it?

**Comment by donovanperalta** [comment]
> @ScriptedAlchemy how much are you charging for the paid plugin, where can we read more about it?

https://app.privjs.com/buy/packageDetail?pkg=@module-federation/nextjs-mf

**Comment by jsnordhealth** [comment]
@ScriptedAlchemy I've been playing around with you're plugin (not sure if this is the right form for this kind of question) but I've been also experiencing the same issue. You can recreate it by in the example `react-nextjs/nextjs-host-react-remote` example by adding a simple ` useState` hook in the `Nav` component in remote.

**Comment by vbbjandrade** [comment]
> @ScriptedAlchemy I've been playing around with you're plugin (not sure if this is the right form for this kind of question) but I've been also experiencing the same issue. You can recreate it by in the example `react-nextjs/nextjs-host-react-remote` example by adding a simple ` useState` hook in the `Nav` component in remote.

I have experienced the same issue. Just cloned the repository and tried the `react-nextjs/nextjs-host-react-remote` example with a simple useState hook like so: 
```
import * as React from 'react';
import { useState } from 'react';

const Nav = () => {
  const [test, setTest] = useState('a');
  return (
    <nav
      style={{
        background: 'cadetblue',
        width: '100%',
        height: '100px',
        color: 'white',
        textAlign: 'center',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '24px',
      }}
    >
      This component is from the Host React App hosted at localhost:8081. {test}
    </nav>
  );
};

export default Nav;
```

And the host app on 8080 throws the following error:

```     
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
  1. You might have mismatching versions of React and the renderer (such as React DOM)
  2. You might be breaking the Rules of Hooks
  3. You might have more than one copy of React in the same app
  See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
  window.console.error @ next-dev.js?878b:25
  printWarning @ react.development.js:207
  error @ react.development.js:181
  resolveDispatcher @ react.development.js:1590
  useState @ react.development.js:1619
  Nav @ Nav.jsx:5
  renderWithHooks @ react-dom.development.js?9c41:16175
  mountIndeterminateComponent @ react-dom.development.js?9c41:20913
  beginWork @ react-dom.development.js?9c41:22416
  callCallback @ react-dom.development.js?9c41:4161
  invokeGuardedCallbackDev @ react-dom.development.js?9c41:4210
  invokeGuardedCallback @ react-dom.development.js?9c41:4274
  beginWork$1 @ react-dom.development.js?9c41:27405
  performUnitOfWork @ react-dom.development.js?9c41:26513
  workLoopSync @ react-dom.development.js?9c41:26422
  renderRootSync @ react-dom.development.js?9c41:26390
  performConcurrentWorkOnRoot @ react-dom.development.js?9c41:25694
  workLoop @ scheduler.development.js?2b4e:266
  flushWork @ scheduler.development.js?2b4e:239
  performWorkUntilDeadline @ scheduler.development.js?2b4e:533
  react.development.js:1620 
        
Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at useState (react.development.js:1620:1)
    at Nav (Nav.jsx:5:33)
    at renderWithHooks (react-dom.development.js?9c41:16175:1)
    at mountIndeterminateComponent (react-dom.development.js?9c41:20913:1)
    at beginWork (react-dom.development.js?9c41:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?9c41:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?9c41:4210:1)
    at invokeGuardedCallback (react-dom.development.js?9c41:4274:1)
    at beginWork$1 (react-dom.development.js?9c41:27405:1)
    at performUnitOfWork (react-dom.development.js?9c41:26513:1)
    at workLoopSync (react-dom.development.js?9c41:26422:1)
    at renderRootSync (react-dom.development.js?9c41:26390:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?9c41:25694:1)
    at workLoop (scheduler.development.js?2b4e:266:1)
    at flushWork (scheduler.development.js?2b4e:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?2b4e:533:1)
```

All webpack configurations including ModuleFederation have been kept the same as the examples.
My company just purchased the license to the Next.js plugin but we have been running into the same issue during development, and if not fixeable we will be forced to remake all our MFEs as class components.

**Comment by ScriptedAlchemy** [comment]
Try sharing react as import false in the remotes config. So it can only use nextjs copy of react

**Comment by vbbjandrade** [comment]
> Try sharing react as import false in the remotes config. So it can only use nextjs copy of react

It does stop the host from throwing the error and the component appears without further issues, but now the remote stops rendering and throws: 

```
Uncaught (in promise) Error: Shared module react doesn't exist in shared scope default
    at ensureExistence (consumes:19:1)
    at consumes:97:1
    at consumes:82:1
    at Object.webpack/sharing/consume/default/react (consumes:134:1)
    at consumes:161:1
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.consumes (consumes:144:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (ensure chunk:5:1)
```

**Comment by LukNasc** [comment]
same problem here
