### ISSUE TITLE
Angular11 Microfrontends Lazy Components demo not working

### ISSUE THREAD

**Issue by KaustubhBadrike-GEP** [module-federation/module-federation-examples#937]
node version: v14.17.1
npm version: 6.14.13
yarn version: 1.22.10

Following steps from [Running the demo section in the README](https://github.com/module-federation/module-federation-examples/tree/master/angular11-microfrontends-lazy-components#running-the-demo)

Fails at "Start the Microfrontend: `yarn start:profile`" step with error as below:

> √ Browser application bundle generation complete.
× ｢wdm｣: HookWebpackError: ENOENT: no such file or directory, open '\package.json'
    at makeWebpackError (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\webpack\lib\Compilation.js:2510:12
    at eval (eval at create (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
    at fn (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\webpack\lib\Compilation.js:452:17)
    at _next3 (eval at create (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:46:1)
    at eval (eval at create (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\webpack\lib\SourceMapDevToolPlugin.js:545:10
    at C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\neo-async\async.js:2857:9)
-- inner error --
Error: ENOENT: no such file or directory, open '\package.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at CacheBackend.provideSync (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
    at WebpackFileSystem.readFileAsUtf8 (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:52:24)
    at PluginChunkReadHandler.getPackageJson (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:35:43)
    at PluginChunkReadHandler.processModule (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:45:40)
    at C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:29:23
    at WebpackModuleFileIterator.internalCallback (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:28:13)
    at WebpackModuleFileIterator.iterateFiles (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:8:9)
    at C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:27:32
× ｢wdm｣: caused by plugins in Compilation.hooks.processAssets
Error: ENOENT: no such file or directory, open '\package.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at CacheBackend.provideSync (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
    at WebpackFileSystem.readFileAsUtf8 (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:52:24)
    at PluginChunkReadHandler.getPackageJson (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:35:43)
    at PluginChunkReadHandler.processModule (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:45:40)
    at C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:29:23
    at WebpackModuleFileIterator.internalCallback (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:28:13)
    at WebpackModuleFileIterator.iterateFiles (C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:8:9)
    at C:\Dump\module-federation-examples\angular11-microfrontends-lazy-components\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:27:32

**Comment by zmrfzn-mitel** [comment]
Getting the same error on a different angular app. 

using the module federation plugin version 1.2.3
yarn: 1.22.10
Angular CLI: 11.2.14
Node: 14.17.5

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1102.14
@angular-devkit/build-angular     0.1102.14
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/core              11.2.14
@angular-devkit/schematics        11.2.14
@angular/cdk                      11.2.13
@angular/material                 10.2.7
@schematics/angular               11.2.14
@schematics/update                0.1102.14
rxjs                              6.6.7
typescript                        4.3.5

p.s for me the demo works just fine
